name: Caching with npm

on: workflow_call

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  job_install_dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Compute dependency cache key
        id: compute_lockfile_hash
        run: echo "::set-output name=hash::${{ hashFiles('package-lock.json') }}"

      - name: Check dependency cache
        uses: actions/cache@v2
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_lockfile_hash.outputs.hash }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: npm install
      # outputs:
      #   dependency_cache_key: ${{ steps.compute_lockfile_hash.outputs.hash }}
      - run: echo "::set-output name=dependency_cache_key::${{ steps.compute_lockfile_hash.outputs.hash }}"
