name: Test

on: push

env:
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  Reusable_Install_Dependencies_Job:
    name: Install Dependencies
    uses: HyeBinYang/actions-practice/.github/workflows/cache-npm.yml@master

  Test_job:
    runs-on: ubuntu-latest
    needs: Reusable_Install_Dependencies_Job
    steps:
      - run: npm ci
      - run: npm test
