name: Test

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v2

      - uses: HyeBinYang/actions-practice/.github/workflows/cache-npm.yml@master
      - run: npm test
