name: Test

on: push

jobs:
  job1:
    uses: HyeBinYang/actions-practice/.github/workflows/cache-npm.yml@master

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v2

      - run: npm test
